# <span style = 'color:Orange'>Ridge Regression</span>
> Multivariate data

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('ad.csv')
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
x = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

### Hyperparameter Tuning

In [4]:
param_grid = {
    'alpha': [0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000],
    'fit_intercept': [True, False],
    'solver': ['auto', 'svd', 'cholesky', 'lsqr', 'sag', 'saga'],
    'positive': [True, False],
    'tol': [1e-5, 1e-4, 1e-3],
}

grid = GridSearchCV(estimator=Ridge(),
                    param_grid=param_grid,
                    cv = 5,
                    scoring='r2',
                    n_jobs=-1)

grid.fit(x_train, y_train)
print('Best paraemters: ',grid.best_params_)

print('Best model : ',grid.best_estimator_)
print('R2 score : ',grid.best_score_)

Best paraemters:  {'alpha': 0.001, 'fit_intercept': True, 'positive': False, 'solver': 'sag', 'tol': 0.001}
Best model :  Ridge(alpha=0.001, solver='sag', tol=0.001)
R2 score :  0.8880479650594209

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
1200 fits failed out of a total of 2880.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 1249, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 922, in fit
    raise ValueError(
ValueError: solver='svd' does not support positive fitting. Please set the solver to 'auto' or 'lbfgs', or set `positive=False`

--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 1249, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 922, in fit
    raise ValueError(
ValueError: solver='cholesky' does not support positive fitting. Please set the solver to 'auto' or 'lbfgs', or set `positive=False`

--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 1249, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 922, in fit
    raise ValueError(
ValueError: solver='lsqr' does not support positive fitting. Please set the solver to 'auto' or 'lbfgs', or set `positive=False`

--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 1249, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 922, in fit
    raise ValueError(
ValueError: solver='sag' does not support positive fitting. Please set the solver to 'auto' or 'lbfgs', or set `positive=False`

--------------------------------------------------------------------------------
240 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 1249, in fit
    return super().fit(X, y, sample_weight=sample_weight)
  File "/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_ridge.py", line 922, in fit
    raise ValueError(
ValueError: solver='saga' does not support positive fitting. Please set the solver to 'auto' or 'lbfgs', or set `positive=False`

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.8879738  0.8879738  0.88797437        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425
 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425
 0.88797397 0.88797734 0.88804797 0.88797429 0.88797395 0.88798586
 0.75683    0.75683    0.75683           nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986
 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986
 0.75683461 0.75679193 0.75687682 0.75682881 0.75681858 0.75672635
 0.8879738  0.8879738  0.88797437        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425
 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425 0.88797425
 0.88797401 0.88797971 0.88795302 0.88797446 0.88797689 0.88796938
 0.75683    0.75683    0.75683           nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986
 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986 0.75682986
 0.75682976 0.7568076  0.75670203 0.75682884 0.75681835 0.75670382
 0.88797381 0.88797381 0.88797439        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88797427 0.88797427 0.88797427 0.88797427 0.88797427 0.88797427
 0.88797427 0.88797427 0.88797427 0.88797427 0.88797427 0.88797427
 0.88797446 0.8879721  0.8879613  0.88797442 0.88797594 0.88797282
 0.75682999 0.75682999 0.75682999        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75682984 0.75682984 0.75682984 0.75682984 0.75682984 0.75682984
 0.75682984 0.75682984 0.75682984 0.75682984 0.75682984 0.75682984
 0.75683032 0.75684909 0.75683195 0.75682915 0.7568177  0.75672295
 0.88797393 0.88797393 0.8879745         nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88797438 0.88797438 0.88797438 0.88797438 0.88797438 0.88797438
 0.88797438 0.88797438 0.88797438 0.88797438 0.88797438 0.88797438
 0.88797424 0.8879734  0.88793538 0.88797434 0.88797468 0.88800405
 0.75682986 0.75682986 0.75682986        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75682972 0.75682972 0.75682972 0.75682972 0.75682972 0.75682972
 0.75682972 0.75682972 0.75682972 0.75682972 0.75682972 0.75682972
 0.75682901 0.75684807 0.75674039 0.75682873 0.7568165  0.75673946
 0.8879751  0.8879751  0.88797567        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88797555 0.88797555 0.88797555 0.88797555 0.88797555 0.88797555
 0.88797555 0.88797555 0.88797555 0.88797555 0.88797555 0.88797555
 0.8879749  0.88795732 0.88800509 0.88797565 0.88797419 0.88797848
 0.75682858 0.75682858 0.75682858        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75682844 0.75682844 0.75682844 0.75682844 0.75682844 0.75682844
 0.75682844 0.75682844 0.75682844 0.75682844 0.75682844 0.75682844
 0.75683411 0.75682022 0.75693994 0.75682773 0.75681748 0.75669955
 0.88798532 0.88798532 0.88798586        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88798578 0.88798578 0.88798578 0.88798578 0.88798578 0.88798578
 0.88798578 0.88798578 0.88798578 0.88798578 0.88798578 0.88798578
 0.88798632 0.88799224 0.88795171 0.88798575 0.88798547 0.88798829
 0.75681408 0.75681408 0.75681408        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75681393 0.75681393 0.75681393 0.75681393 0.75681393 0.75681393
 0.75681393 0.75681393 0.75681393 0.75681393 0.75681393 0.75681393
 0.75682048 0.75683549 0.75688625 0.75681285 0.75680326 0.7567001
 0.88795731 0.88795731 0.88795767        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88795781 0.88795781 0.88795781 0.88795781 0.88795781 0.88795781
 0.88795781 0.88795781 0.88795781 0.88795781 0.88795781 0.88795781
 0.88795853 0.88795514 0.88793212 0.88795764 0.88795779 0.88796007
 0.75651477 0.75651477 0.75651477        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.75651465 0.75651465 0.75651465 0.75651465 0.75651465 0.75651465
 0.75651465 0.75651465 0.75651465 0.75651465 0.75651465 0.75651465
 0.75650996 0.75653954 0.75666335 0.75651228 0.75650001 0.75630078
 0.88155729 0.88155729 0.88155493        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.88155744 0.88155744 0.88155744 0.88155744 0.88155744 0.88155744
 0.88155744 0.88155744 0.88155744 0.88155744 0.88155744 0.88155744
 0.88155741 0.88155573 0.88157034 0.88155709 0.88155393 0.88149685
 0.74584406 0.74584406 0.74584406        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.74584419 0.74584419 0.74584419 0.74584419 0.74584419 0.74584419
 0.74584419 0.74584419 0.74584419 0.74584419 0.74584419 0.74584419
 0.74584371 0.74586648 0.74555477 0.74583998 0.74580197 0.74543069]
  warnings.warn(

In [5]:
# model training with best hyper parameters
rid = grid.best_estimator_
rid

Ridge(alpha=0.001, solver='sag', tol=0.001)

In [6]:
y_Pred = rid.predict(x_test)

print('Intercept :', rid.intercept_)
print('Coef :', rid.coef_)
print('r2_score : ',r2_score(y_test, y_Pred))

Intercept : 4.7080615751782595
Coef : [0.0545447  0.10090801 0.00439022]
r2_score :  0.9058662640633134

In [7]:
print('CV R2:', grid.best_score_)
print('Test R2:', r2_score(y_test, y_Pred))

CV R2: 0.8880479650594209
Test R2: 0.9058662640633134

In [15]:
# correlation matrix
df.corr()

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [19]:
x_range = np.linspace(x['TV'].min(),  x['TV'].max())
y_range = np.linspace(x['Radio'].min(), x['Radio'].max())

xx,yy = np.meshgrid(x_range, y_range)
news_mean = df['Newspaper'].mean()
news_col = np.full(xx.ravel().shape, news_mean)
pred_ip = np.c_[xx.ravel(), yy.ravel(), news_col]

zz = rid.predict(pred_ip).reshape(xx.shape)



fig = px.scatter_3d(df, x = df['TV'],
                    y = df['Radio'],
                    z = df['Sales'],
                    color=df['Sales'],
                    color_continuous_scale='thermal',
                    title='True data')
fig.add_surface(x = x_range, y = y_range, z = zz, colorscale='thermal')

fig.show()

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but Ridge was fitted with feature names